name: ds_hrm
description: The official app for Divisional Secretariat  - Bandarawela

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  easy_localization:
  #stacked service
  stacked:
  stacked_services:
  stacked_themes:

  #firebase
  firebase_core_web:
  firebase_core:
  firebase_auth:
  firebase_auth_web:
  cloud_firestore:
  cloud_firestore_web:
  firebase_storage:
  firebase_storage_web:

  image_picker:
  google_fonts:
  shimmer:
  cached_network_image:
  url_launcher:
  responsive_builder:
  auto_size_text: ^3.0.0-nullsafety.0
  line_icons:
  animations:
  animated_text_kit:
  #date
  flutter_datetime_picker:
  carousel_slider:
  uuid:
  percent_indicator:

  rxdart:






dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/translation/
